
server:
  port: 8080
spring:
  application:
    name: spring-boot-rabbitmq
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/temperature
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    port: 15672
    exchange: temperature.exchange
    queue: temperature.queue
    routingKey: temperature.routingKey
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true